# Generated by Django 3.2.12 on 2022-02-16 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TrackingCode', models.CharField(max_length=50, null=True)),
                ('Gender', models.CharField(max_length=20, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Contact', models.CharField(max_length=20, null=True)),
                ('Address', models.CharField(max_length=20, null=True)),
                ('Status', models.CharField(max_length=20, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(max_length=50, null=True, upload_to='')),
                ('Role', models.CharField(max_length=20, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250, null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineLocationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(max_length=250, null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineHistoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VaccinationType', models.CharField(max_length=50, null=True)),
                ('VaccinatedBy', models.CharField(max_length=250, null=True)),
                ('Remark', models.CharField(max_length=350, null=True)),
                ('CreationDate', models.DateTimeField(auto_now_add=True)),
                ('UpdationDate', models.DateField(null=True)),
                ('indivisuals', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.individuallist')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.memberlist')),
                ('vaccinelocations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinelocationlist')),
                ('vaccines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinelist')),
            ],
        ),
        migrations.AddField(
            model_name='memberlist',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinelocationlist'),
        ),
        migrations.AddField(
            model_name='memberlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
