# Generated by Django 3.2.12 on 2022-02-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individuallist',
            name='user',
        ),
        migrations.AddField(
            model_name='individuallist',
            name='FirstName',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='individuallist',
            name='LastName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
