# Generated by Django 3.2.12 on 2022-02-17 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0002_auto_20220217_1707'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccinehistorylist',
            old_name='indivisuals',
            new_name='individuals',
        ),
        migrations.AlterField(
            model_name='memberlist',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccinelocationlist'),
        ),
    ]
