# Generated by Django 3.2.12 on 2022-02-18 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_alter_vaccinehistorylist_individuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinehistorylist',
            name='individuals',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.individuallist'),
        ),
    ]
