# Generated by Django 3.2.12 on 2022-02-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_alter_vaccinehistorylist_individuals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individuallist',
            name='Address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='individuallist',
            name='Contact',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='individuallist',
            name='Status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
